services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql
  taproom-offering-engine:
    depends_on: 
      - db
    build:
      dockerfile: ./build/app/Dockerfile
    command: sh -c "npx prisma migrate dev --name init && npm run start"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

volumes:
  pg_data:
