
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Read directly rather than with prisma/config's env(), which throws when it's unset.
    // `prisma generate` (run on every npm install, see package.json) doesn't connect to the
    // database, and DATABASE_URL isn't set while Docker images are being built.
    url: process.env.DATABASE_URL ?? "",
  },
});
